const envConstants = {
    PORT: 5000,
    NODE_ENV: "development",
    MONGO_URI: "mongodb://user:password@localhost:27017/scrape_verse_db?authSource=admin",
    CORS_ORIGIN: "*",
    FRONTEND_URL: "http://localhost:3000",
    ACCESS_TOKEN_SECRET: "super_secret_access_jwt_key_change_in_production",
    REFRESH_TOKEN_SECRET: "super_secret_refresh_jwt_key_change_in_production",
    BCRYPT_ROUNDS: 10,
    MISTRAL_API_KEY: "",
    BRIGHT_DATA_API_KEY: "",
    BRIGHT_DATA_PROXY_URL: "",
    BRIGHT_DATA_ZONE: "web_unlocker",
    BRIGHT_DATA_SERP_ZONE: "serp",
    BRIGHT_DATA_CUSTOMER_ID: "",
    BRIGHT_DATA_ZONE_PASSWORD: "",
    BRIGHT_DATA_COUNTRY: "",
    GEMINI_API_KEY: "",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: 587,
    SMTP_USER: "",
    SMTP_PASS: "",
    SENDING_USER: "scrape-verse <noreply@example.com>",
    SEND_MAIL: false,
    GOOGLE_CLIENT_ID: "",
    GOOGLE_CLIENT_SECRET: "",
    GOOGLE_REDIRECT_URI: "http://localhost:5000/api/auth/google/callback",
} as const;

export default envConstants;
